### ISSUE TITLE
[Bug] Adding Bearer token to GraphQL request fails with `undefined method 'permissions' for #<Doorkeeper::AccessToken id`

### ISSUE THREAD

**Issue by ToshY** [hummingbird-me/kitsu-server#1562]
**Problem**

Adding Bearer token to GraphQL fails with the following response:

```json
{
  "error": {
    "message": "undefined method `permissions' for #<Doorkeeper::AccessToken id: <omitted>, resource_owner_id: <omitted>, application_id: nil, token: [FILTERED], refresh_token: [FILTERED], expires_in: 2592000, revoked_at: nil, created_at: \"2024-12-21 20:08:12.037385000 +0000\", scopes: \"public\">"
  },
  "data": {}
}
```

**Solution**

Looking at recent changes, I assume this is caused by https://github.com/hummingbird-me/kitsu-server/commit/57b3a36fe15844197ae33539cb6b995ff86abf2b.

Should probably be `current_user&.resource_owner&.permissions` instead (?)

**Comment by ToshY** [comment]
Fixed in https://github.com/hummingbird-me/kitsu-server/commit/8aea8670e133b1f315ed46c74c34a46a73015ae5
